### ISSUE TITLE
Draft & Verify

### ISSUE THREAD

**Issue by Ryu1845** [lucidrains/speculative-decoding#2]
Does this repository implement [Draft & Verify](https://arxiv.org/abs/2309.08168)?

**Comment by lucidrains** [comment]
@Ryu1845 hey! thanks for sharing that paper!

that looks quite close to the early exit strategy (but i think they predict which layers to skip) - but using the same model for drafting is definitely what i was going for.

i think my prophet transformer idea should be the best though (although i'm biased and still haven't ran any head to head 😆 )

**Comment by lucidrains** [comment]
@Ryu1845 really think we are going to see a resurgence in adaptive computation research over the next year, like actually made practical

**Comment by Ryu1845** [comment]
I think so too, thanks again for your work. 
it looks like the official code for the paper will be uploaded [here](https://github.com/dilab-zju/self-speculative-decoding), but I'll keep an eye on this repo too :wink:

**Comment by lucidrains** [comment]
@Ryu1845 sounds good!

yea i think the main idea from the prophet is to take advantage of the cached last layer embedding from the large model, which should be superior to any early exit stuff. if you find me another paper that did that, would definitely read and implement

**Comment by lucidrains** [comment]
@Ryu1845 ohh yes, they totally did. so the only difference is i use a small transformer as the medusa / prophet heads

ok let me cite them as well

**Comment by lucidrains** [comment]
@Ryu1845 oh haha, they don't have a paper, just a github repo

**Comment by Ryu1845** [comment]
I'm guessing they'll release a paper once they've got a working prototype :smile:  
It looks like it's still a WIP https://github.com/FasterDecoding/Medusa/issues/3

**Comment by lucidrains** [comment]
@Ryu1845 ohh, so it isn't functional yet? maybe i'll send their group a message. solving batched spec decoding is a bit tricky

**Comment by lucidrains** [comment]
> ~~I'm guessing they'll release a paper once they've got a working prototype 😄 ~~ ~It looks like it's still a WIP [FasterDecoding/Medusa#3](https://github.com/FasterDecoding/Medusa/issues/3)~ I actually don't know if it's running yet :/

so it works or doesn't work?

**Comment by Ryu1845** [comment]
it looks like it works, I'm sorry for the misunderstanding on my side

**Comment by lucidrains** [comment]
nice! that's amazing, i believe in that approach

**Comment by lucidrains** [comment]
i'll have to read their code next week and see how they approach batching

**Comment by jmamou** [comment]
@lucidrains 
Amazing work!
Do you plan to release your results with early exit?
Thanks
