### ISSUE TITLE
Speculative Decoding State Reversion after Rejection

### ISSUE THREAD

**Issue by breaddaerb** [lucidrains/speculative-decoding#3]
Hi, I've been working with the speculative decoding implementation in the provided codebase. I'm curious about the output sequence `out` when the predictions made by the smaller model (small_net) are rejected by the larger model (net). Upon a rejection, we should revert the state of out to its condition prior to the rejected predictions.  However, it appears that the current implementation of `speculative_decoding` function does not perform this state reversion.
Say if the original `seq_len` is 128 and `gamma` is 5, if all of them are rejected then in this iteration the `seq_len` should be 128+1, but not 128+5+1.

**Comment by j-geuter** [comment]
Second this - it seems to me like this is a major bug in the current implementation. Would be awesome if you could fix this!

**Comment by lucidrains** [comment]
@j-geuter sorry i missed this issue

it has been a while, but on a quick glance, i thought [this line of code](https://github.com/lucidrains/speculative-decoding/blob/main/speculative_decoding/speculative_decoding.py#L212) should do it?

**Comment by j-geuter** [comment]
Hey! Doesn't seem to me like it - that only determines how many more samples you generate right? But the rejected samples are still added to `out`. You'd have to make sure only accepted samples are added to out. (In particular, in the batch setting, the lengths of the decoded sequences will diverge, and in each iteration, you'll have to ensure the small model starts decoding each sequence at the correct index.)

**Comment by lucidrains** [comment]
@j-geuter oh i see

barely remember my thought process, but think i attempted to take care of this [here](https://github.com/lucidrains/speculative-decoding/blob/main/speculative_decoding/speculative_decoding.py#L217) during the right alignment, but fail to do so for batch size of 1

**Comment by lucidrains** [comment]
@j-geuter let me stare at this a bit more tomorrow morning and get it fixed, thank you!

**Comment by j-geuter** [comment]
To be fair I didn't really look at the if-clause for `batch_size>1`, seems like that could be handling it correctly for larger batches. Just noticed for `batch_size=1` it doesn't.

**Comment by j-geuter** [comment]
Ok thank you!

**Comment by lucidrains** [comment]
@j-geuter actually, want to just check to see if the latest change fixes things?

**Comment by j-geuter** [comment]
Yes thanks, for `batch_size=1` this looks correct now! (I didn't check for `batch_size>1` though)

**Comment by lucidrains** [comment]
nice! yea, i think batch size > 1 is accounted for [here](https://github.com/lucidrains/speculative-decoding/blob/main/speculative_decoding/speculative_decoding.py#L210), but feel free to reopen if it breaks when you increase the batch size

**Comment by lucidrains** [comment]
@j-geuter working ok?

**Comment by breaddaerb** [comment]
@lucidrains hi, I test the current version on my project. For `batch_size=1` it works fine. For `batch_size > 1`, there seem to be some minor issues. Specifically, I believe the line [here](https://github.com/lucidrains/speculative-decoding/blob/3194f53502760289b7a7bdb0bd1d1e37d8c829c9/speculative_decoding/speculative_decoding.py#L210) should be:
```
seq_offset_indices = seq_arange - num_rejected[..., None]
```
given `out` is the result of concatenating all `gamma` tokens with the previou one. After making this modification, the generation results seem to be normal.
I'm not sure if I misunderstood your code, but could you please take another look?

**Comment by lucidrains** [comment]
@breaddaerb i don't think that's quite right, as that would push the sequence into negative indices

could not understand my thought process from a year agop, so i completely redid it with my updated skillset..

seems to work fine, could you double check for me? thank you

**Comment by lucidrains** [comment]
don't even think batch size > 1 is necessary for research on this topic, more of something industrial labs would care about

**Comment by breaddaerb** [comment]
@lucidrains I test it on my project and it works fine! Agree that `batch_size==1`  is probably enough for research purposes lol.

**Comment by lucidrains** [comment]
@breaddaerb nice! yeah, had a real "wtf did I write" when reviewing that logic this morning

good luck with your research

**Comment by j-geuter** [comment]
@lucidrains sorry I missed this as I have just been using my own implementation now, so I haven't tested yours since, but thank you for the update!

**Comment by lucidrains** [comment]
@j-geuter nice! good luck with your research
