### ISSUE TITLE
Question about Decoder :  10 layers & 3 layers for each 

### ISSUE THREAD

**Issue by jiminlx** [lucidrains/speculative-decoding#6]
Thank you for your contribution about speculative decoding. 

I am just undergraduate student, interested in Efficient LLM. 

Although the code came out a long time ago, I have one simple question about the part of this code.

I can observe that for each drafter and verifier model, it is used that :
`
model = Decoder(
    num_tokens = 256,
    dim = 512,
    depth = 10
).to(device)
`
`
small_model = Decoder(
    num_tokens = 256,
    dim = 512,
    depth = 3
).to(device)
`

For each. 

I can understand the smaller model does have less params because of less `dim`, but I am wondering that the smaller model cannot actually generate text tokens precisely by just cutting off the layers. 

Is this just simple implement? Or even though just cutting off the layers, does the text prediction is similar as larger models'? 

Again, thank you for your clear code!!

**Comment by lucidrains** [comment]
hey no problem Jimin

not sure if i fully understand your question, but if it is why i chose to limit depth rather than model dimension, it was completely arbitrary. you can probably do a full hyperparameter search on the smaller model to see which combination gives the best speed up

**Comment by lucidrains** [comment]
@easyminnn actually surprised people are still interested in the repo! feel like there should be a lot of spec decode implementation out there by now..
